{% set version = "1.0.0" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: bb5cdacaa498bba72d78a5243da30ff0f620635c1db9bc8be7a1f4ac7a110ca7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python
    - qtpy

test:
  requires:
    - pyqt
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
