{% set version = "1.0.2" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: 771dd95ac4f50d647d18b4e892fd310a580b56d258476554c7b3498593dfd887

build:
  number: 0
  skip: true  # [ppc64le]
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  build:
      - {{ cdt('mesa-libgl') }}  # [linux]
  run:
    - python >=3.6
    - qtpy

test:
  requires:
    - pyqt
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
