{% set version = "1.1.1" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: ec02e200231fa68a146a93845890aa0432a7edcba14bf811ff6975cf9acdab5d

build:
  number: 0
  # we did not support earlier versions of qtawesome for ppc64le or s390x
  skip: true  # [ppc64le or s390x or py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - qta-browser=qtawesome.icon_browser:run
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  build:
    - {{ cdt('mesa-libgl') }}  # [linux]
  run:
    - python
    - qtpy

test:
  requires:
    - pyqt
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - pip
    - python
  commands:
    - pip check
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Iconic fonts in PyQt and PySide applications
  dev_url: https://github.com/spyder-ide/qtawesome
  doc_url: https://qtawesome.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
