{% set version = "0.5.5" %}

package:
  name: qtawesome
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/q/qtawesome/QtAwesome-{{ version }}.tar.gz
  sha256: 742de5f559cbaf2523d73c9c0ad622878ab1b1b3892c6727b6e91d9118496179

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  build:
      - {{ cdt('mesa-libgl') }}  # [linux]
  run:
    - six
    - python
    - qtpy

test:
  requires:
    - pyqt
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE
  summary: Iconic fonts in PyQt and PySide applications

extra:
  recipe-maintainers:
    - SylvainCorlay
    - goanpeca
    - ccordoba12
