{% set name = "qtawesome" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qtawesome-{{ version }}.tar.gz
  sha256: 783e414d1317f3e978bf67ea8e8a1b1498bad9dbd305dec814027e3b50521be6

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - qta-browser=qtawesome.icon_browser:run

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - qtpy

test:
  requires:
    - pyqt
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - pip
  commands:
    - pip check
  imports:
    - qtawesome

about:
  home: https://github.com/spyder-ide/qtawesome
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: Iconic fonts in PyQt and PySide applications
  description: QtAwesome enables iconic fonts such as Font Awesome and Elusive Icons in PyQt and PySide applications.
  dev_url: https://github.com/spyder-ide/qtawesome
  doc_url: https://qtawesome.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - ccordoba12
    - dalthviz
