travis:
  secure:
    BINSTAR_TOKEN: Smqa+pNNzzzpehABC+R2ve6tOAGPw6rS2ET4HKiEgD3Z8+yAY4ECYcP8RwGmUtPlEC72Ra3SWNm8nRg67GlX+v/qtctTOSL/tQnPK8aohr8TiGGn90XLvt4C3JnJr7CTwXO/xHoH8r+a7yEDcsT0JW+c2HOvrKGfedFrI3N79qaWLg4YYxIo7ZCiqcywg5rry1UD3FmB8sheKoyVB7U8ATRhv8sh41Wlb4y2oxAmhMyoGsbQw8sc+j6iFDloZSznmDQBMBadbRdcNHmwzQPj1ZgMp7QmqjvZHYuJ79Rjc+raKCA9i6u/DFa5HPgRZUmVwpphjZeOcSWf18Q5DbAxwkibZVdIa6rlTj8KyoyI9jIXZsxJPj2rsKx81Fkgr5Ywj6Y9OBNSOQEP+wc+C31UusSUHOGGF946/iHm3KZpS+rQCcrS3id7Ry1HJbd7U5sh4ackrJoIreCJavwyUPa7883VEEXcDQC4I+OzO7uSK098TIT8JxOOn7/V6N2JarYS4sZ6e2+2+4AAFWS/cy4at9anx0oP7jVCGBwO/tnVeZtTopdZtVLpkT7WlLtfbtG5v8H1AeBDQLOsw9gsD+N78CkvKWiEpfVbLerw2H1oJxZgb/MslhAdOE19l9fgyhSBjYYrO1DLiTr/ScRtHv4pf6jD1wpFUvN+xCbqe9Fx38k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
