travis:
  secure:
    BINSTAR_TOKEN: Bzkc6Zz/AZaO6KB6sTm08fPZcLYfFweCWlRqaTTwJhRxIXnh9xyW5bPoJQJXKvfySFEg7SaHpNTbv1iBa/cZe2umG/+l5OZ5HylW4jOBsoaeK2qrIfqIAEYvvuuzV4wufKQe4EudYvA/p6cTypBgYhCX/7xsW4QcNQid81vnfacqjuHz+zpursq5oGSlcZfV8ZBdD8f/cJjJ7H7L+7C5q0lh3ZtUV76c2t+SdZrEkLM0FPGm/nbG5UYU0IMrgWeG0V6vPu7XVWRAk5QoY40ZN+BK+kC3w0IxB773x4lTZO2BAMWKsrno4iTJliHiV08Ma0PqZFCXL7QLcgTFzHnXvn5gIcRdPvOE6L/5tgpGPW+Im02HWCr/u8f9w2BMtm/W6dRyymmeZjE/Up+4eurjOrDrVnLzRMmDdgwP0U0a/2wG5Bf8vXkU2P956rigQkjAKJBXVsjLqkGMJoOGyHQu2y/GT0OeeqBca5nBuF9UcNlwEuWAALbOtnQxXdCEOtkcUx1RwCADcNoF/P5xU8TNKNmpqk5q9rQIB79jlZuR0n5qwzi+6lUnwz8r9xjZBq4PIAFet8FyyxNO5HO83pHLL5QilFLTgbe8ltcg307/Onxha87MPjoLSIcAsNZBDf43mXsUlfLdPmVALTFCrpeL4/Dq1pva4WzV7mu+jqm9m0I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
